apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients-api
  namespace: clients-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clients-api
  template:
    metadata:
      labels:
        app: clients-api
    spec:
      containers:
        - name: clients-api
          image: docker.io/yourusername/clients-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017/clients"
---
apiVersion: v1
kind: Service
metadata:
  name: clients-api-service
  namespace: clients-api
spec:
  selector:
    app: clients-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
