apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: clients-api-cert
spec:
  secretName: clients-api-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: clients.api.deltacapita.com
  dnsNames:
    - clients.api.deltacapita.com
