apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clients-api
  template:
    metadata:
      labels:
        app: clients-api
    spec:
      containers:
      - name: clients-api
        image: clients-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/clientsdb
